name: findx_admin
description: admin dashboard for app findx

publish_to: none

version: 0.0.1+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0

  # state
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.3

  # UI
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  dropdown_button2: ^2.3.9

  # DI
  injectable: ^2.1.2
  get_it: ^7.6.0

  # Data
  dio: ^5.3.3
  graphql: ^5.1.3
  shared_preferences: ^2.2.2

  # Util
  flutter_dropzone: ^3.0.6
  collection: ^1.17.0
  logger: ^2.0.2+1
  flutter_dotenv: ^5.1.0
  go_router: ^12.1.1

  findx_dart_client:
    git:
      url: git@github.com:FindX-0/findx_dart_client.git

  common_models:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_models

  common_widgets:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_widgets

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.4.6
  injectable_generator: ^2.1.6
  freezed: ^2.4.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/
    - .env.local
    - .env.development
    - .env.production
